-- =====================================================
-- DLTJ2.10
-- DATABASE SEED
-- =====================================================
--
-- The main application data is restored from:
-- dltj210_backup.sql
--
-- Working Tool tables are created by:
-- migrations.sql
--
-- No additional seed data is required currently.
-- =====================================================